// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendToTerminal(arg1:string,arg2:string):Promise<void>;

export function StartTerminal(arg1:string,arg2:string):Promise<void>;
