// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendToTerminal(arg1, arg2) {
  return window['go']['main']['App']['SendToTerminal'](arg1, arg2);
}

export function StartTerminal(arg1, arg2) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2);
}
